# Site settings
title: "Real World Go"
description: "Real World Go aims at releasing articles, tutorials, and screencasts targeted for applications in the real world."
baseurl: ""
url: "http://www.realworldgo.com"
twitter: realworldgo
youtube: realworldgo
googleplus: "https://plus.google.com/114095242175921008597"

# Build settings
markdown: kramdown
permalink: /:categories/:title
