# Site settings
title: "Real World Go"
description: "Real World Go aims at releasing articles, tutorials, and screencasts targeted for applications in the real world."
baseurl: ""
url: "http://www.realworldgo.com"
twitter: realworldgo
youtube: realworldgo
googleplus: "https://plus.google.com/114095242175921008597"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: "/:categories/:title"
relative_permalinks: false
paginate: 5
paginate_path: "page/:num"
encoding: "utf-8"
sass:
    style: :compressed
